#ifndef CLU_UNDEF_MACROS_HEADER
#define CLU_UNDEF_MACROS_HEADER

#ifdef CLU_MACROS_HEADER
#   undef CLU_MACROS_HEADER
#endif

#ifdef CLU_GCC_COMPILERS
#   undef CLU_GCC_COMPILERS
#endif
#ifdef CLU_MSVC_COMPILERS
#   undef CLU_MSVC_COMPILERS
#endif

#undef CLU_GCC_WNO_CAST_FUNCTION_TYPE
#undef CLU_GCC_RESTORE_WARNING

#undef CLU_SINGLE_RETURN

#endif
