# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'clu'
copyright = '2021, Chlorie'
author = 'Chlorie'


# -- C++ information ---------------------------------------------------------

primary_domain = 'cpp'
default_role = 'cpp:any'
highlight_language = 'cpp'
cpp_index_common_prefix = ['clu::']


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['breathe']

breathe_default_project = 'clu'
breathe_default_members = ()

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'
html_search_language = 'zh'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['custom']
html_css_files = ['custom.css']


# -- Read the Docs support ---------------------------------------------------

import os, subprocess

def config_doxyfile():
    with open('Doxyfile.in', 'r') as f:
        s = f.read()
    s = s.replace('@PROJECT_SOURCE_DIR@', '..')
    with open('Doxyfile', 'w') as f:
        f.write(s)

if os.environ.get('READTHEDOCS', None) == 'True':  # On RtD
    config_doxyfile()
    subprocess.call('doxygen', shell=True)
    breathe_projects = {'clu': './xml'}
