name: Build docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - uses: actions/checkout@v2
        with:
          ref: 96316ba6baaede1de9a5e188ab001ec6f88b8434
          path: docs
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: standardese
          channels: conda-forge,defaults
          channel-priority: true
          show-channel-urls: true
      - name: Install standardese
        run: |
          conda install standardese
          standardese -V
      - name: Build docs
        run: |
          python main/docs/build.py docs
      - name: Push docs
        run: |
          cd docs
          git config --global push.default simple
          git config user.name "Github Actions"
          git config user.email "action@github.com"
          git add -A
          git commit -m "Update docs"
          git push -f origin HEAD:gh-pages
